# Nombre de la aplicación
spring.application.name=eventia-backend

# CONEXIÓN ORACLE CLOUD (DOCKER FRIENDLY)
# Quitamos la ruta fija ?TNS_ADMIN=... porque la definiremos en el Dockerfile
spring.datasource.url=jdbc:oracle:thin:@eventiadb_tp

#Base de Datos (Usamos una variable de entorno para la pass)
spring.datasource.username=ADMIN
spring.datasource.password=${DB_PASSWORD}

# 2. JWT Secret (Definimos una variable para que JwtUtil la lea)
# El valor después de los dos puntos es un "valor por defecto" para cuando trabajas en tu PC local
jwt.secret=${JWT_SECRET:DeLeNiLoGaHeToDaVa_Eventia_123456789}

# Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# --- Seguridad ---
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.security.user.name=
spring.security.user.password=

server.port=8080