spring.application.name=eventia-backend

# Conexión Oracle Cloud
# Usamos la variable de entorno del sistema
#WALLET_PATCH = cambiar por ruta de descarga de wallet

#spring.datasource.url=jdbc:oracle:thin:@eventiadb_tp?TNS_ADMIN=WALLET_PATH
spring.datasource.url=jdbc:oracle:thin:@eventiadb_tp?TNS_ADMIN=C:/OracleWallets/EventiaDB
# Credenciales
spring.datasource.username=ADMIN
spring.datasource.password=Eventia2025!

#Excluir generaci�n de seguridad por defecto
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
#Evitar que se genere el usuario por defecto
spring.security.user.name=
spring.security.user.password=


# Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Esto "traduce" las clases Java a Tablas Oracle automáticamente
spring.jpa.hibernate.ddl-auto=update

# Cambiar puerto 
server.port=8081